# Generated by Django 6.0.3 on 2026-04-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
