# Generated by Django 6.0.3 on 2026-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0005_remove_booking_status_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='rooms/default.jpg', upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
